[general]
import = ["~/dotfiles/themes/alacritty-current.toml"]
live_config_reload = true

[font]
normal = { family = "Berkeley Mono", style = "Regular" }
# normal = { family = "DinaRemasterII", style = "Regular" }
size = 16
# normal = { family = "IBM 3270", style = "Regular" }
# size = 17

[cursor]
style = { shape = "Block", blinking = "Always" }
