theme = "default-min"

[editor]
line-number = "relative"
true-color = true
soft-wrap.enable = true
auto-format = false
auto-pairs = false

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[keys.normal."space"]
# m = ":run-shell-command make"
# c = ":run-shell-command cargo build"
# t = ":run-shell-command cargo test"
t = ":sh cargo test &"

[keys.normal]
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal."]"]
g = ["save_selection", "goto_next_change"]

[keys.normal."["]
g = ["save_selection", "goto_prev_change"]
