theme = "default-min"

[editor]
line-number = "relative"
true-color=true
soft-wrap.enable=true

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[keys.normal."space"]
# m = ":run-shell-command make"
# c = ":run-shell-command cargo build"
# t = ":run-shell-command cargo test"
t = ":sh cargo test &"

[keys.normal]
X = ["extend_line_up", "extend_to_line_bounds"]
