client.focused          #44EAA4 #44EAA4 #000000 #44EAA4 #44EAA4
client.focused_inactive #CCCCCC #FFFFFF #000000 #FFFFFF #FFFFFF
client.unfocused        #E0E0E0 #FFFFFF #000000 #FFFFFF #FFFFFF
client.urgent           #2f343a #900000 #ffffff #900000 #000000
client.placeholder      #FFFFFF #FFFFFF #000000 #FFFFFF #FFFFFF
client.background       #FFFFFF

bar {
    position top
    workspace_buttons yes
    status_command i3blocks
    tray_output primary
    colors {
        background #FFFFFF
        statusline #000000

        separator  #666666

        focused_workspace  #44EAA4 #44EAA4 #000000
        active_workspace   #333333 #222222 #FFFFFF
        inactive_workspace #FFFFFF #FFFFFF #000000
        urgent_workspace   #2F343A #900000 #FFFFFF
        binding_mode       #2F343A #900000 #FFFFFF
    }
}
